// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVs45FkL0Tt_kN8nnqrhIBwSi-KvG0uUs',
    appId: '1:674514117095:web:35e1a13740c2abcffa1d42',
    messagingSenderId: '674514117095',
    projectId: 'mysr-6fac0',
    authDomain: 'mysr-6fac0.firebaseapp.com',
    storageBucket: 'mysr-6fac0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0w02P66gKqpB5VAMovXAUHsmN5Q7IfA',
    appId: '1:674514117095:android:72e15d066193b462fa1d42',
    messagingSenderId: '674514117095',
    projectId: 'mysr-6fac0',
    storageBucket: 'mysr-6fac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDinOMaVxbZrKTmsYFbT9VZZPKz7Q-UbBA',
    appId: '1:674514117095:ios:94292b8075f0a3b0fa1d42',
    messagingSenderId: '674514117095',
    projectId: 'mysr-6fac0',
    storageBucket: 'mysr-6fac0.appspot.com',
    iosClientId: '674514117095-rtsv5i333vmo1fg14ch1q3u20ilo7ipk.apps.googleusercontent.com',
    iosBundleId: 'com.mysr.mysrapp',
  );
}
